name: uv-lock-report

"on":
  pull_request:
    paths:
      - uv.lock
    branches:
      - renovate/lock-file-maintenance

jobs:
  report:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Report
        uses: mw-root/uv-lock-report@v0.12.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-format: table
